
package matteogabburo.document.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "local-db-service", targetNamespace = "http://ws.document.matteogabburo/", wsdlLocation = "http://localhost:6902/ws/local-db-service?wsdl")
public class LocalDbService
    extends Service
{

    private final static URL LOCALDBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCALDBSERVICE_EXCEPTION;
    private final static QName LOCALDBSERVICE_QNAME = new QName("http://ws.document.matteogabburo/", "local-db-service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6902/ws/local-db-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCALDBSERVICE_WSDL_LOCATION = url;
        LOCALDBSERVICE_EXCEPTION = e;
    }

    public LocalDbService() {
        super(__getWsdlLocation(), LOCALDBSERVICE_QNAME);
    }

    public LocalDbService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCALDBSERVICE_QNAME, features);
    }

    public LocalDbService(URL wsdlLocation) {
        super(wsdlLocation, LOCALDBSERVICE_QNAME);
    }

    public LocalDbService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCALDBSERVICE_QNAME, features);
    }

    public LocalDbService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalDbService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalDBInterface
     */
    @WebEndpoint(name = "LocalDB_implementationPort")
    public LocalDBInterface getLocalDBImplementationPort() {
        return super.getPort(new QName("http://ws.document.matteogabburo/", "LocalDB_implementationPort"), LocalDBInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalDBInterface
     */
    @WebEndpoint(name = "LocalDB_implementationPort")
    public LocalDBInterface getLocalDBImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.document.matteogabburo/", "LocalDB_implementationPort"), LocalDBInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCALDBSERVICE_EXCEPTION!= null) {
            throw LOCALDBSERVICE_EXCEPTION;
        }
        return LOCALDBSERVICE_WSDL_LOCATION;
    }

}
