
package serviceadaptor.document.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdaptorService_interface", targetNamespace = "http://ws.document.serviceadaptor/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdaptorServiceInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_user_from_remote")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_user_from_remote", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.GetUserFromRemote")
    @ResponseWrapper(localName = "get_user_from_remoteResponse", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.GetUserFromRemoteResponse")
    @Action(input = "http://ws.document.serviceadaptor/AdaptorService_interface/get_user_from_remoteRequest", output = "http://ws.document.serviceadaptor/AdaptorService_interface/get_user_from_remoteResponse")
    public String getUserFromRemote();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_motivation_phrase")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_motivation_phrase", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.GetMotivationPhrase")
    @ResponseWrapper(localName = "get_motivation_phraseResponse", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.GetMotivationPhraseResponse")
    @Action(input = "http://ws.document.serviceadaptor/AdaptorService_interface/get_motivation_phraseRequest", output = "http://ws.document.serviceadaptor/AdaptorService_interface/get_motivation_phraseResponse")
    public String getMotivationPhrase();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "save_user_in_remote")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save_user_in_remote", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.SaveUserInRemote")
    @ResponseWrapper(localName = "save_user_in_remoteResponse", targetNamespace = "http://ws.document.serviceadaptor/", className = "serviceadaptor.document.ws.SaveUserInRemoteResponse")
    @Action(input = "http://ws.document.serviceadaptor/AdaptorService_interface/save_user_in_remoteRequest", output = "http://ws.document.serviceadaptor/AdaptorService_interface/save_user_in_remoteResponse")
    public String saveUserInRemote();

}
