
package matteogabburo.document.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalDB_interface", targetNamespace = "http://ws.document.matteogabburo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalDBInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns matteogabburo.document.ws.User
     */
    @WebMethod(operationName = "get_user_by_auth")
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "get_user_by_auth", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.GetUserByAuth")
    @ResponseWrapper(localName = "get_user_by_authResponse", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.GetUserByAuthResponse")
    @Action(input = "http://ws.document.matteogabburo/LocalDB_interface/get_user_by_authRequest", output = "http://ws.document.matteogabburo/LocalDB_interface/get_user_by_authResponse")
    public User getUserByAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns matteogabburo.document.ws.User
     */
    @WebMethod(operationName = "get_user_by_id")
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "get_user_by_id", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.GetUserById")
    @ResponseWrapper(localName = "get_user_by_idResponse", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.GetUserByIdResponse")
    @Action(input = "http://ws.document.matteogabburo/LocalDB_interface/get_user_by_idRequest", output = "http://ws.document.matteogabburo/LocalDB_interface/get_user_by_idResponse")
    public User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns matteogabburo.document.ws.User
     */
    @WebMethod(operationName = "update_user")
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "update_user", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.UpdateUser")
    @ResponseWrapper(localName = "update_userResponse", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.UpdateUserResponse")
    @Action(input = "http://ws.document.matteogabburo/LocalDB_interface/update_userRequest", output = "http://ws.document.matteogabburo/LocalDB_interface/update_userResponse")
    public User updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns matteogabburo.document.ws.User
     */
    @WebMethod(operationName = "delete_user")
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "delete_user", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.DeleteUser")
    @ResponseWrapper(localName = "delete_userResponse", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.DeleteUserResponse")
    @Action(input = "http://ws.document.matteogabburo/LocalDB_interface/delete_userRequest", output = "http://ws.document.matteogabburo/LocalDB_interface/delete_userResponse")
    public User deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns matteogabburo.document.ws.User
     */
    @WebMethod(operationName = "create_user")
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "create_user", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.CreateUser")
    @ResponseWrapper(localName = "create_userResponse", targetNamespace = "http://ws.document.matteogabburo/", className = "matteogabburo.document.ws.CreateUserResponse")
    @Action(input = "http://ws.document.matteogabburo/LocalDB_interface/create_userRequest", output = "http://ws.document.matteogabburo/LocalDB_interface/create_userResponse")
    public User createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
